#!/usr/bin/env python
from sys import argv

log=open("/home/a/backlightlog",'a')
log.write("RUN")
bf="/sys/class/leds/smc::kbd_backlight/%s"
step=25

def _get_int(file_name):
    return int(open(file_name).read())

def _set_brightness(val):
    x=open(bf%"brightness",'w')
    x.write(str(val))
    x.close()

current_brightness = _get_int(bf%"brightness")
max_brightness = _get_int(bf%"max_brightness")

op = -1 if argv[1]=='dec' else 1
new_brightness = max(0, min(255, current_brightness + (step * op)))
_set_brightness(new_brightness)
log.write("RAN")
log.close()
